spring:
  datasource:
    url: ${MY_POSTGRES_URL} #jdbc:postgresql://localhost:5432/jlpt
    username: ${MY_POSTGRES_USER}
    password: ${MY_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true