server:
  port: 80

spring:
  datasource:
    url: ${MY_POSTGRES_URL}
    username: ${MY_POSTGRES_USER}
    password: ${MY_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true

webdriver: ${MY_WEBDRIVER}